import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { ArrowRight, Zap, Users, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import LeadCaptureForm from '@/components/LeadCaptureForm';
export default function Home() {
    const [showForm, setShowForm] = useState(false);
    return (_jsxs("div", { className: "min-h-screen bg-white", children: [_jsx("header", { className: "sticky top-0 z-50 bg-white border-b", children: _jsxs("nav", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between", children: [_jsx("div", { className: "font-bold text-xl text-primary-600", children: "FounderPlane" }), _jsx(Link, { to: "/login", className: "text-primary-600 hover:text-primary-700 font-medium", children: "Admin" })] }) }), _jsxs("main", { children: [_jsx("section", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20", children: _jsxs("div", { className: "text-center", children: [_jsx("h1", { className: "text-5xl font-bold tracking-tight mb-6", children: "Know Your Founder Stage" }), _jsx("p", { className: "text-xl text-gray-600 mb-8 max-w-2xl mx-auto", children: "Discover where you are in your founder journey and get personalized guidance to scale your business." }), _jsxs("button", { onClick: () => setShowForm(!showForm), className: "bg-primary-600 hover:bg-primary-700 text-white px-8 py-3 rounded-lg font-medium inline-flex items-center gap-2 transition", children: ["Start Assessment ", _jsx(ArrowRight, { size: 20 })] })] }) }), _jsx("section", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16", children: _jsx("div", { className: "grid md:grid-cols-3 gap-8", children: [
                                { icon: Zap, title: 'Quick Assessment', desc: 'Get insights in 5 minutes' },
                                { icon: Users, title: 'Expert Guidance', desc: 'Learn from experienced founders' },
                                { icon: TrendingUp, title: 'Actionable Plan', desc: 'Clear path to your next milestone' },
                            ].map(({ icon: Icon, title, desc }, i) => (_jsxs("div", { className: "p-6 bg-gray-50 rounded-lg", children: [_jsx(Icon, { className: "text-primary-600 mb-4", size: 32 }), _jsx("h3", { className: "font-bold text-lg mb-2", children: title }), _jsx("p", { className: "text-gray-600", children: desc })] }, i))) }) }), showForm && (_jsx("section", { className: "bg-gray-50 py-20", children: _jsxs("div", { className: "max-w-2xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsx("h2", { className: "text-3xl font-bold mb-8 text-center", children: "Get Started Today" }), _jsx("div", { className: "bg-white p-8 rounded-lg shadow-lg", children: _jsx(LeadCaptureForm, { sourcePage: "home", onSuccess: () => setShowForm(false) }) })] }) }))] }), _jsx("footer", { className: "border-t bg-gray-50 py-8", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-gray-600", children: _jsx("p", { children: "\u00A9 2024 FounderPlane. All rights reserved." }) }) })] }));
}
